apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-db
  name: secret-db
spec:
  containers:
  - image: nginx
    name: secret-pod
    env:
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-creds
            key: user
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-creds
            key: pass
