apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-configuration
  name: test-configuration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
