apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 10
      template:
        spec:
          containers:
          - name: busycorn
            image: busybox
            command: ["curl",  "test.in/ping"]
          restartPolicy: OnFailure  
