apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-service
  name: test-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 32001
  selector:
    app: svc
  type: NodePort
status:
  loadBalancer: {}
