apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-selector
  name: test-selector
spec:  
  selector:
     matchLabels:
       app: nginx             
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
      nodeSelector:
        disk: ssd
