apiVersion: v1
kind: Pod
metadata:
  name: test-pv-pod
spec:
    containers:
    - name: pvc-pod
      image: nginx
      volumeMounts:
      - mountPath: /mydata
        name: datavolume
    volumes:
    - name: datavolume
      persistentVolumeClaim:
        claimName: test-pvc
